version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hr_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: jojoabs9

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306" # Alterando a porta local para 3307
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hr_management
